# Generated by Django 6.0.1 on 2026-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Required. 150 characters or fewer.', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
