# Generated by Django 6.0.1 on 2026-01-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_productsizemodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='nmain_imadge',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='Main Image'),
        ),
    ]
