# Generated by Django 6.0.1 on 2026-01-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_productmodel_nmain_imadge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='nmain_imadge',
            new_name='main_imadge',
        ),
    ]
