# Generated by Django 6.0.1 on 2026-01-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_nmain_imadge_productmodel_main_imadge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='main_imadge',
            new_name='main_image',
        ),
    ]
